Feature/goal
chemo-wakate/tutorial-6th pull request #15
Opened 2017-09-27 02:39 UTC by maskot1977

各ステップの冒頭に「目標」を書きました。また、計算結果は出さないことにしました。

2017-09-27 02:43 UTC, yamasakih commented
MergeしたのにPull Requestが残ってる？？

2017-09-27 08:56 UTC, kubor requested changes
masterのマージが不要なのでrebaseをお願いします

2017-09-30 00:25 UTC, maskot1977 commented
もう一度レビューをお願いします

2017-09-30 00:25 UTC, kubor approved these changes

2017-09-30 00:26 UTC, merged

2017-09-30 00:26 UTC, kubor commented
LGTM!!